---
- name: Install EPEL release for nginx
  yum: name=epel-release state=present

- name: Install nginx
  yum: name=nginx state=present
  notify:
    - start nginx

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  service: name=nginx state=started enabled=yes

